"""Formatting helpers for RedThread memory index files."""

from __future__ import annotations

from datetime import datetime, timezone

from redthread.core.defense_synthesis import DeploymentRecord

HEADER = (
    "# RedThread Threat Knowledge Base\n\n"
    "This file is auto-generated by the Defense Synthesis Engine.\n"
    "Each entry represents a confirmed jailbreak and its validated guardrail fix.\n\n"
    "---\n\n"
)

_ENTRY_TEMPLATE = """\
## {timestamp} | {category} | {severity}
**Trace:** `{trace_id}`
**Scope:** model=`{model}` | prompt_hash=`{prompt_hash}`
**Attack vector:** {attack_vector}

> **Guardrail clause:** {clause}

**OWASP ref:** {owasp_ref} | **MITRE ATLAS:** {mitre_ref}
**Validated:** {validated_str}

---

"""


def format_entry(record: DeploymentRecord) -> str:
    """Render one memory entry as markdown."""
    validation = record.validation
    status = "✅ YES" if validation.passed else "❌ NO"
    benign_suffix = ""
    if validation.benign_checks:
        passed = sum(1 for check in validation.benign_checks if check.passed)
        benign_suffix = f" | benign pack: {passed}/{len(validation.benign_checks)}"
    validated_str = f"{status} (residual score: {validation.judge_score:.2f}{benign_suffix})"
    return _ENTRY_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        category=record.classification.category,
        severity=record.classification.severity,
        trace_id=record.trace_id,
        model=record.target_model,
        prompt_hash=record.target_system_prompt_hash,
        attack_vector=record.classification.attack_vector or "N/A",
        clause=record.guardrail_clause,
        owasp_ref=record.classification.owasp_ref,
        mitre_ref=record.classification.mitre_atlas_ref,
        validated_str=validated_str,
    )


__all__ = ["HEADER", "format_entry"]
